# 服务端口
server:
  port: 8110
# 服务名
spring:
  application:
    name: guli-edu

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://139.224.229.212:3306/xczx?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      pool-name: GuliHikariPool
      maximum-pool-size: 12
      connection-timeout: 60000
      minimum-idle: 10
      idle-timeout: 500000
      max-lifetime: 540000
      connection-test-query: SELECT 1
  jackson:
    date-format: yyyy-MM-dd  HH:mm:ss
    time-zone: GMT+8


#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  level:
    root: WARN

mybatis-plus:
  global-config:
    db-config:
      logic-not-delete-value: 0
      logic-delete-value: 1
  mapper-locations: classpath:com/ketai/edu/mapper/xml/*.xml

#指定注册中心地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8220/eureka/
#eureka服务器上获取的是服务器的ip地址，否则是主机名
  instance:
     prefer-ip-address: true

